version: "2"
linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
formatters:
  enable:
    - gofmt
